---

# @see https://docs.ansible.com/ansible/latest/modules/service_module.html
- name: restart ssh
  service:
    name: "{{ 'sshd' if ( ansible_os_family == 'RedHat' ) else 'ssh' }}"
    state: restarted

...
