
language: generic

env:
  global:

    - AWS_ACCESS_KEY_ID=AKIAJMVNAJPFFHMZRBTA
    - AWS_DEFAULT_REGION=ap-southeast-2
    - SNS_ARN=arn:aws:sns:ap-southeast-2:873114526714:codebuild-notifications

    # AWS_SECRET_ACCESS_KEY
    - secure: U1+OFn7Lcz/4n0Dm1Suoh2goum7bmeJJzYDroFZEmzRF3/NfxLXl7hrC6QKinxSgCPGBhVN5feJLUZE3WD4QPi6f/s8OStYtFTsUEH5WwQgNOF/gtbicLlLOT6URnmj9uzFiEeQYhEUjGfq2qSkvOrA4OcJRpnOz56X2X+RqPNKkcg4MVHaBNgGHVomtMtbEzI/mGw5RWpa+ATewX/adHYTKe31h6IqxDMZom6HdfdzRYQIrBzbtmookn9riGJEc9FRqD2caWO+mAjtyqgOrPXXyRrRqLC2DKoujWe9roqyLuZ/Gq3tUHWxQDSlBQmKNr6/9spGe7ZpWKPlZWYMPel5eKVRI+vM90seeF5LlFcDPeYHhqO1zr1QrlbgMXcoPjGkbnsJax+RFMv2N44pLifjnUzompKB9FvWs3p9tfh7KZZ3KXHdfjkENY38ZLAfBAqnHNLxMb7PU3+HQDsdkYfoloYOHBqVE55J5db/5BFriqNpFgNnJ1ZE1Rj3eF/R7b7h1WxquE0afZ6MyiQF1XWbyWC5L5cBioGRGw32tfrpeugyzbKoxatLjMXYHebvUvKQOOuNmP7256WCeZxEDPQf33FiPUSPRvQ5r3ZdXikP6am5VcpH4REJPep45VL/VrRGhqBSBdK99wF3cCklNbPybL+tor/zZ51nGdpiKFN4=

    # CLOUDFLARE_EMAIL
    - secure: rPXtZGNvWU4Rey1jzkb5SGCJkfu1d1cwEoQpxBxL+HyTYiH/Yy7niXMrqPea1TGu4UvvCTTfjC/FAsN4OSgpDXN384GGGp3Oygaf5teqyzTBF8yygIuJGWHUChBlf1ap4hznXXHUesZY8bAIF+ScNK5q7D/GltnYOCEIGvnXrf47eUk09abjRHXZImEMVpoaBoHHm5shEVDaUqgKB8Tb6HFsZLbM3+/XwBhEeG54t4T7qoA6kDBHdiRlqsBxf8W6QByUDVxoqCQccVM2RSmrvrtZgMKY9syiM2ZHb43sJmjiYoBln6ZFvgkfx5IC+YY22R1UQ6hFg3g+cgVl4mspcqsdKPhabvPMrZDb7LzXARmZUqDkSI8rTEbd7rbVU3/gaTe7f5eL/w4ZsTBT+f++a9PvcpRh1sM9pbz9o5yEDGGcYlaa/uWCFBGSC38AmT8bT5dghBi3/aPq7rZWhU805YRFOpElsWpQ3XMyfo2X204/FqtGOz11V9f4YTbv/IA/O0NnzBgXcG4gusJFuN/kxgW2Hrj9HX4q8NtX8ol1LZaSsj6lYVC4RaErm4hF7Hq7E8yWZywbT8WIUDHsb0CL85Nvq7HRxfNlTU5ekQYFZEkIoLLM5pMYN+y2LBBySfzaggFnsZgNKm9d1ne5MQmlbaA/0Lx8rF6+jTOdnDM1Kqc=

    # CLOUDFLARE_TOKEN
    - secure: Z7pDH1tuBosDxpsMGp2Gk1gTIwQ6zfhgEFcaEos3/ui1I3V8uDPNXKyVs7iPyU5aRWnKhopgFxhpDm71AnhnyvwqIGNpsjmp0fQC0eQ/hY6T44OuWnulx2i9m7wXj2caeiGMYAl8NJqwWte8E9E9cVzrSmAxJrnojrjKrZhYRaW5MPAGa+ZRSAYockGk/evbIOJj8emOXc5ucdNFIqKir6U676dIkbTQ4rPGE0THT3F2YdWoJSluOtW2KtU8eO9RM0O+Sy3u9iHZXElyKKCRvlcLTCXQTwDrpn9Wt833vtouZC1zGnc/vesIHvRDYMRKx+PZ0NcUU/ZD+VbwGL1pSgvOIYzhoMX/ZUHb9E2iqGWezhS/MWCWCqgW4dEfQvbQEEycl6nBY3fecrrvnw/hnSDK2tkZVt1/OU+iEvjYdxR8Menc8smnNjK05fny7KYD8Ns4q+6YGD+riNMEQ7+HsnQDwMDYpkjgCcsgXFR60vcQciZeqkD+4vms325q3RRwI64datd1rX6M58VUjaUAXJis2qbDWfYsPiyNNXRw0w6Fip/0TU/qyX3pxRpaUJeH9ICmVcuFMrrkoKpxX+754RW1Oj2dP/ltsWUf7X5idMQ5mmNPNV8dIr6Z+joRLN5k4bsLLb13bIzTnrBg50t47lt1AyAHl24gv0vAPjIcu8A=

    # DATADOG_API_KEY
    - secure: wUj3r697Dh8I7mJcS3wlMP0WJcxKo1+nRSK3FkYXp2Zl4M0pIIBjK1oUnIg5Bstyg1hEU5UO8aWsyPm18rsO1pbPv/8aImoQ5YQzyiTt3xuz3o1+fyQvmUIhRm16K+bWVfPcuBvg8Z97OCOxmCa98mAAdw9M77dE+nJqk/IWbKrNN3l6PfyplqQ8J8TfaPWsNrkI4ILGcJf44+ji9gfpgbWf3kSW4lKZUh2bVz9LU6yogQ1zYZUm8dTm57niF9O4caenYfKBZVyeHTk8cMZULtyug5zstGs7o3usaXO/mpK7ngs0IzPk5XtvuAwO6s9+H863OVPcLamTNZb2skI1t+jnEEb7Rvqib2a5b5dF3GOVxf/nMMRa8KdSZ5cAnjW7yZZA1ONS7UyICKFYPS2KIysi9lquYoIqAPI1G9WFiPwreAGKPUGJis5l/QUIDcsQ0zrb/L03ZJ+xpBROnLxhTBtPaZIoWNNI7nkqZCIrIMczdt7KJ8Bs4KkfMMdG2b4uaoRRNWZ1Pg6BDoEc9Z5bopP1lbxx6jf/KnsXQaCS9ZBVmBHTLzjqoGxMMhK9kLiqGfzNdeEXrPjaNjhs+AQRcUDO9FQNZoZcbyEAHggwKnueabfCaQqd7OkgHorweQ0nUDsuKvUR65jtRKLfuih2sNGnQ5U5jMA1x9tZbdEoGRc=

    # DATADOG_APP_KEY
    - secure: RDcH51hYNol7fQmBCdcHXuh5qk+M1KK73XBuYCtHdTOx2IYoe7ZX4C7VNSzDBW4wrhFxtB/ghF12vftW68PPvGhW6db76hZ22oAKf+OXEb3ac+MUhzcImCqhaxDjTSiJD0H/pTRCa5gQ8GF5upX2ttYe06pLIUHigClnTnBKOvaE7YkW2mp2GsSIrob/mmzk/pmhv/ndC92t6Q24ACKxUjt9r3Liqdg2dmIOY5bH0/5bSJOUvwj12j05ov4TpxgvopwCLIRGwE2sVAAnxiUpX2i/tFNHfkxSyejBCIoQSHvVYcVkCetoUNRYmRvmZqrh/7U1yfJZ0sZLPygZAGPRIdI8h545tfvqK5iVc8fYadoTBN1zS8Gas+wqCPqMtOFi+124Z2dK8sWm3iwIILroZpxGuBANAb8T9SmuSfCBEKHlL/VJZGIkRbwq2FcZQSWOx98GAVbJLeBQygOibRdHPLAC9nSROEaGPZixrxNwb89WyP7NJlVMrqmkX3+0q6ub/cP1eygMavmoolWm5BFwA1+Kua9Z7rekLkfeKtrQBHc7pFGY026JE1Pi1hHtjPsqQOeduMBufpjXuEpYPnVr5QQb9nBystNhilFByoPbN0E7Gkg4sCiy0s+fz+7xmsTdzQLiCM183zi05u9Jr/aazKYucfJJ47cS3uF1rn+Bhwc=

    # SLACK_HOOK
    - secure: SVoBDhMo+JvwRV7mvINNgpLd2TCcmVF7vdZinfvTGpeGdAlWcI4d4rjOb0ZAiEybuxDOQrJ78wIoqvLc1dzaUiX9BAgynmxEdZq2ayo9zPJehuZdxEFA45jlGE6YAqLmszKvTOWZDNzcgNB9XXb8RwSvmLMljdIx7I9Q5tHeirYAWuzjJqVh4j82ewnFE8aoQl36HuDS4mEJU8OrQh9laXUwoesbRFSTkRdaA78p0Huuxw5Xt/5Z9LccfeSAqnjXCs3lUTVizlWJEiNj6wzityW+AbRrwzG+WRjqyAcnSOPkeKfCVraW0OMzyzNMJmqQJtBlmT7wqEQCKVRKcM1li95325WxVx2MxoNe5XjBabPhsUSnl+EhLnw7W15R8XY5RpjDhsnYc7hHM1fO3D2irhC7DXs7cNDQsi7KwDmLrM7021dMvgB3nWAkuwh2KeWIiHmoVzIXwwRJEj9n1zZqeWA9DkOBMLJL/iBv01PQG1MdwB2tm6vjR0fqp5lNgsNCZBelhQRecBPVWaaA9ykwvTLwyAxziG6n+p0V6qqVMa+EaYYOtTUZ73S7zXARd7UX6Vt8QEqDTDH+UfKQW5+wwtEuohvFi3hen6z60HjLdqpu9AHMJQGVkqC7BY8jfequzqgI0F0M4lYF+Xd054dYj54PK2h/aE6yvKc+hAggAEo=

    # SSH_PORT
    - secure: LMFdtTRfofUacpCa6ET+T9heWQUdXz2q5ZESTjhhIO/pqhrAQsVd0jfZ5bu0mjj0hPNDpQQpdBvqhzXsU7V48R1NBJ1t3pE9KCvsxhGzMM/UwBaEwxlWfxmAHKbUPmTzyLmBX9Dh+iTOkZjwRXI1MoYhZlDo/Lut6fGqRbolk6vg8VsZWsaN16Aw+EbPq37v29tCURty5qQPZ8KlUvhmjylHDpeynr7zLDl7NmJyq1iaNTkXB5dh9EdA538o940LcXhV61CfBe2756cgsg40sRbNV+rgbSF5+gHoYJ0WRzO7tEoig8gPocNQwAofxdjuJOI4H2bNqtHndlCO+nabhe7gDre7QQC2K0Tq7KZ7RXHmD4IrUMQ6sqSSldmk8UmyE1ZqnRLTKkBD1pDvk0s/6VytKDpp24LhHGi0NQDszUFtT+P2JmZfBmfCqvuQQeCNC31X+7k2nfsyqm5IsxYIsgfwz1AGPb+B4bKvYFscPwv8PerGa45gRo63ZSoRbhwaa8vmDHu45T0HVM9ZCaSaSjTOo+5BpdypOQvyLWhrsJAoQCuoGjb4SfmvB4UmcJm8YqZYMNCGuvwLvr7cA+YKmZiXKHzG3faO2gsyQDUTBY3MUDg9yjtBXn7MN+2HS8QiqLH8ZEgkTs9kH+ceeyZNWSIzrpnq4oScup00tzIvfCc=

before_install:

  # Install the latest version of Shellcheck and make it available to the shell.
  - curl --location --fail --silent https://storage.googleapis.com/shellcheck/shellcheck-latest.linux.x86_64.tar.xz > shellcheck.tar.xz
  - tar --xz -xvf shellcheck.tar.xz
  - shellcheck() { "${TRAVIS_BUILD_DIR}/shellcheck-latest/shellcheck" "$@"; }
  - export -f shellcheck

install: ./install.sh

before_script:

  # Make Terraform and Packer binaries available to the shell.
  - terraform() { "${TRAVIS_BUILD_DIR}/terraform" "$@"; }
  - export -f terraform
  - packer() { "${TRAVIS_BUILD_DIR}/packer" "$@"; }
  - export -f packer

script: ./script.sh

notifications:
  email: false
  webhooks:
    urls: https://api.tm.id.au/v2/travis/jobStatus
  slack:
    on_start: always
    rooms:
      - secure: IJtgZLdA6E0DPF33SvMHdXw5tl4P8mB5ZmJUHU2kAOQ7RH3dHjsLuzyVXpxk1y1P5g5GtM1+Jcycd9Jn3PC/D1zK/x/76VvK4BcJPYaJJU62zajBak9BMgV4dCWmaFFbnVx3HozOVmck8IpX7z6EAIpa7gOnrMHAQK3KmwxafpwqDjvVVOKrchSBQ1JAABUfSmVZDpFG8JZREXu47PznPsVaQ0wgo9v9Z8+YCSr6W2z5UwjjE+K5LktJWP2Ob55EVn3PChw5uKk0zrA8tkM9V7lRWLEloUYJ/wY/2VCdc1C2ganwDNkOEz5ph2R0kRx90SqxE61zPmRO5+dcxGtttvOnAonngOuCbVErDj62awxP4qPaZooV6/TgLvQAUb0IavvO24iejcM9OCMrfrVqNxk7ruKkVOBopvPM21YvibtONIiUFEZaz2jMhTSqrvl7jTugLUxlOtiYBQOD5fNVwLiW9g2NvwMI72pAZTX9Ufq7d8blI2nBa1/wSkA7beS+qtKY2Th7tAf+RER3OuvQnZfGriBeuCSaJNexmzql8Aci6F4CKDWB+L2o1pxc2gvsAWesOWmO2jm6igpQ2vRhR8jyS81SOppm9YRWmt79mcUpiJhDV64Hjlbri/rOfqwXgUY8b7HiAUTSXrdrGtb7E+iZhKceJceCet563sr1qx0=
