
language: generic

env:
  global:

    - AWS_ACCESS_KEY_ID=AKIAJMVNAJPFFHMZRBTA
    - AWS_DEFAULT_REGION=ap-southeast-2

    # AWS_SECRET_ACCESS_KEY
    - secure: U1+OFn7Lcz/4n0Dm1Suoh2goum7bmeJJzYDroFZEmzRF3/NfxLXl7hrC6QKinxSgCPGBhVN5feJLUZE3WD4QPi6f/s8OStYtFTsUEH5WwQgNOF/gtbicLlLOT6URnmj9uzFiEeQYhEUjGfq2qSkvOrA4OcJRpnOz56X2X+RqPNKkcg4MVHaBNgGHVomtMtbEzI/mGw5RWpa+ATewX/adHYTKe31h6IqxDMZom6HdfdzRYQIrBzbtmookn9riGJEc9FRqD2caWO+mAjtyqgOrPXXyRrRqLC2DKoujWe9roqyLuZ/Gq3tUHWxQDSlBQmKNr6/9spGe7ZpWKPlZWYMPel5eKVRI+vM90seeF5LlFcDPeYHhqO1zr1QrlbgMXcoPjGkbnsJax+RFMv2N44pLifjnUzompKB9FvWs3p9tfh7KZZ3KXHdfjkENY38ZLAfBAqnHNLxMb7PU3+HQDsdkYfoloYOHBqVE55J5db/5BFriqNpFgNnJ1ZE1Rj3eF/R7b7h1WxquE0afZ6MyiQF1XWbyWC5L5cBioGRGw32tfrpeugyzbKoxatLjMXYHebvUvKQOOuNmP7256WCeZxEDPQf33FiPUSPRvQ5r3ZdXikP6am5VcpH4REJPep45VL/VrRGhqBSBdK99wF3cCklNbPybL+tor/zZ51nGdpiKFN4=

    # CLOUDFLARE_EMAIL
    - secure: rPXtZGNvWU4Rey1jzkb5SGCJkfu1d1cwEoQpxBxL+HyTYiH/Yy7niXMrqPea1TGu4UvvCTTfjC/FAsN4OSgpDXN384GGGp3Oygaf5teqyzTBF8yygIuJGWHUChBlf1ap4hznXXHUesZY8bAIF+ScNK5q7D/GltnYOCEIGvnXrf47eUk09abjRHXZImEMVpoaBoHHm5shEVDaUqgKB8Tb6HFsZLbM3+/XwBhEeG54t4T7qoA6kDBHdiRlqsBxf8W6QByUDVxoqCQccVM2RSmrvrtZgMKY9syiM2ZHb43sJmjiYoBln6ZFvgkfx5IC+YY22R1UQ6hFg3g+cgVl4mspcqsdKPhabvPMrZDb7LzXARmZUqDkSI8rTEbd7rbVU3/gaTe7f5eL/w4ZsTBT+f++a9PvcpRh1sM9pbz9o5yEDGGcYlaa/uWCFBGSC38AmT8bT5dghBi3/aPq7rZWhU805YRFOpElsWpQ3XMyfo2X204/FqtGOz11V9f4YTbv/IA/O0NnzBgXcG4gusJFuN/kxgW2Hrj9HX4q8NtX8ol1LZaSsj6lYVC4RaErm4hF7Hq7E8yWZywbT8WIUDHsb0CL85Nvq7HRxfNlTU5ekQYFZEkIoLLM5pMYN+y2LBBySfzaggFnsZgNKm9d1ne5MQmlbaA/0Lx8rF6+jTOdnDM1Kqc=

    # CLOUDFLARE_TOKEN
    - secure: Z7pDH1tuBosDxpsMGp2Gk1gTIwQ6zfhgEFcaEos3/ui1I3V8uDPNXKyVs7iPyU5aRWnKhopgFxhpDm71AnhnyvwqIGNpsjmp0fQC0eQ/hY6T44OuWnulx2i9m7wXj2caeiGMYAl8NJqwWte8E9E9cVzrSmAxJrnojrjKrZhYRaW5MPAGa+ZRSAYockGk/evbIOJj8emOXc5ucdNFIqKir6U676dIkbTQ4rPGE0THT3F2YdWoJSluOtW2KtU8eO9RM0O+Sy3u9iHZXElyKKCRvlcLTCXQTwDrpn9Wt833vtouZC1zGnc/vesIHvRDYMRKx+PZ0NcUU/ZD+VbwGL1pSgvOIYzhoMX/ZUHb9E2iqGWezhS/MWCWCqgW4dEfQvbQEEycl6nBY3fecrrvnw/hnSDK2tkZVt1/OU+iEvjYdxR8Menc8smnNjK05fny7KYD8Ns4q+6YGD+riNMEQ7+HsnQDwMDYpkjgCcsgXFR60vcQciZeqkD+4vms325q3RRwI64datd1rX6M58VUjaUAXJis2qbDWfYsPiyNNXRw0w6Fip/0TU/qyX3pxRpaUJeH9ICmVcuFMrrkoKpxX+754RW1Oj2dP/ltsWUf7X5idMQ5mmNPNV8dIr6Z+joRLN5k4bsLLb13bIzTnrBg50t47lt1AyAHl24gv0vAPjIcu8A=

install:

  # Install Terraform.
  - curl --location https://releases.hashicorp.com/terraform/0.11.7/terraform_0.11.7_linux_amd64.zip > terraform.zip
  - unzip terraform.zip
  - terraform() { "${TRAVIS_BUILD_DIR}/terraform" "$@"; }

  # Install Packer
  - curl --location https://releases.hashicorp.com/packer/1.2.2/packer_1.2.2_linux_amd64.zip > packer.zip
  - unzip packer.zip
  - packer() { "${TRAVIS_BUILD_DIR}/packer" "$@"; }

script:

  # Find all Terraform config directories and Packer templates.
  - TERRAFORM_DIRS="$( find . -name "main.tf" | sort | xargs dirname )"
  - PACKER_TEMPLATES="$( find . -name "packer.json" | sort )"

  # Check that Terraform config files are formatted correctly and that they validate - whichever
  # directory they may be in.
  - terraform fmt -check
  - echo "${TERRAFORM_DIRS}" | xargs -I % bash -c 'echo "\n%" && ( cd % && terraform init -input=false -lock=false )'
  - echo '\nValidating all Terraform files...'
  - echo "${TERRAFORM_DIRS}" | xargs -I % bash -c 'echo "%" && ( cd % && terraform validate )'

  # Check that the state is up-to-date - i.e. that no changes have been pushed without being
  # applied. We only care about the exit code here, and don't want to expose any potentially
  # sensitive data, so we also redirect the output.
  - echo '\nChecking there are no outstanding changes to be applied...'
  - echo "${TERRAFORM_DIRS}" | xargs -I % bash -c 'echo "%" && ( cd % && terraform plan -detailed-exitcode -lock=false > /dev/null )'

  # Shellcheck any shell scripts.
  - shellcheck **/*.sh

  # Check that all Packer templates validate & build - whichever directory they may be in.
  # TODO: Deregister these AMIs afterwards so that builds are idempotent.
  - echo "${PACKER_TEMPLATES}" | xargs -I % bash -c 'echo % && ( cd $( dirname % ) && packer validate $( basename % ) )'
  - echo "${PACKER_TEMPLATES}" | xargs -I % bash -c 'echo % && ( cd $( dirname % ) && packer build $( basename % ) )'

notifications:
  email: false
  webhooks:
    urls: https://api.tm.id.au/v2/travis/jobStatus
  slack:
    on_start: always
    rooms:
      - secure: IJtgZLdA6E0DPF33SvMHdXw5tl4P8mB5ZmJUHU2kAOQ7RH3dHjsLuzyVXpxk1y1P5g5GtM1+Jcycd9Jn3PC/D1zK/x/76VvK4BcJPYaJJU62zajBak9BMgV4dCWmaFFbnVx3HozOVmck8IpX7z6EAIpa7gOnrMHAQK3KmwxafpwqDjvVVOKrchSBQ1JAABUfSmVZDpFG8JZREXu47PznPsVaQ0wgo9v9Z8+YCSr6W2z5UwjjE+K5LktJWP2Ob55EVn3PChw5uKk0zrA8tkM9V7lRWLEloUYJ/wY/2VCdc1C2ganwDNkOEz5ph2R0kRx90SqxE61zPmRO5+dcxGtttvOnAonngOuCbVErDj62awxP4qPaZooV6/TgLvQAUb0IavvO24iejcM9OCMrfrVqNxk7ruKkVOBopvPM21YvibtONIiUFEZaz2jMhTSqrvl7jTugLUxlOtiYBQOD5fNVwLiW9g2NvwMI72pAZTX9Ufq7d8blI2nBa1/wSkA7beS+qtKY2Th7tAf+RER3OuvQnZfGriBeuCSaJNexmzql8Aci6F4CKDWB+L2o1pxc2gvsAWesOWmO2jm6igpQ2vRhR8jyS81SOppm9YRWmt79mcUpiJhDV64Hjlbri/rOfqwXgUY8b7HiAUTSXrdrGtb7E+iZhKceJceCet563sr1qx0=
