---

# @see http://docs.ansible.com/ansible/latest/modules/file_module.html
# @see http://docs.ansible.com/ansible/latest/modules/mount_module.html
# @see https://docs.aws.amazon.com/console/efs/mount-considerations

- name: Ensure /home/{{ username }}/efs dir exists for EFS mount.
  file:
    path: /home/{{ username }}/efs
    state: directory
    owner: "{{ username }}"
    group: "{{ username }}"
  tags:
    - mounts

- name: Mount EFS target.
  mount:
    path: /home/{{ username }}/efs
    src: "{{ efs_id_1 }}.efs.{{ aws_region }}.amazonaws.com:/"
    fstype: nfs4
    opts: nfsvers=4.1,rsize=1048576,wsize=1048576,hard,timeo=600,retrans=2
    state: mounted
  tags:
    - mounts

- name: Ensure /home/{{ username }}/downloads dir exists for EFS mount.
  file:
    path: /home/{{ username }}/efs
    state: directory
    owner: "{{ username }}"
    group: "{{ username }}"
  tags:
    - mounts

- name: Mount EFS target.
  mount:
    path: /home/{{ username }}/downloads
    src: "{{ efs_id_2 }}.efs.{{ aws_region }}.amazonaws.com:/"
    fstype: nfs4
    opts: nfsvers=4.1,rsize=1048576,wsize=1048576,hard,timeo=600,retrans=2
    state: mounted
  tags:
    - mounts

- name: Ensure /var/www dir exists for EFS mount.
  file:
    path: /var/www
    state: directory
    owner: root
    group: root
  tags:
    - mounts

- name: Mount EFS target.
  mount:
    path: /var/www
    src: "{{ efs_id_3 }}.efs.{{ aws_region }}.amazonaws.com:/"
    fstype: nfs4
    opts: nfsvers=4.1,rsize=1048576,wsize=1048576,hard,timeo=600,retrans=2
    state: mounted
  tags:
    - mounts

...
