---

# TODO: Finish this based on the ubuntu.yml when that is completed.

# TODO: Add Bamboo installation (./tasks/bamboo.yml).
# TODO: Add Ansible Tower or AWX installation.

- hosts: default
  become: yes

  vars:
    username: tim
    full_name: Tim Malone
    email: tdmalone@gmail.com
    timezone: Australia/Melbourne
    ssh_key: https://raw.githubusercontent.com/tdmalone/dotfiles/master/ssh.pub
    shell: /bin/bash # TODO: Set to zsh once that's installed.
    hostname: centos.tm.id.au
    new_system: false # WARNING: Should only be used on brand new servers!
    ssh_port: "{{ lookup('env', 'SSH_PORT') }}"

  handlers:

    - name: restart ssh
      service:
        name: sshd
        state: restarted

  tasks:

    - name: Include tasks common to all distros.
      include_tasks: ./tasks/common.yml

...
