---

# TODO: Finish this playbook!
# TODO: Find a way to test this playbook, perhaps with Travis CI Mac support.

- hosts: mac
  become: no

  roles:

    - { role: homebrew,         tags: [ "homebrew",         "packages" ] }
    - { role: hostname,         tags: [ "hostname",         "config" ] }
    - { role: papertrail,       tags: [ "papertrail",       "packages" ] }
    - { role: git,              tags: [ "git",              "config" ] }
    - { role: package-managers, tags: [ "package-managers", "packages" ] }

    # TODO: Enable once it supports Mac.
    #- { role: keybase,          tags: [ "keybase",          "packages" ] }

    - { role: hashicorp,        tags: [ "hashicorp",        "packages" ] }
    - { role: go,               tags: [ "go",               "packages" ] }
    - { role: nginx,            tags: [ "nginx",            "packages", "config" ] }
    - { role: lastpass,         tags: [ "lastpass",         "packages" ] }

    - { role: notifications,    tags: [ "notifications" ] }

...
