---

# TODO: Finish this playbook!
# TODO: Find a way to test this playbook, perhaps with Travis CI Mac support.

- hosts: mac
  become: no

  roles:

    # Generic common roles.
    - { role: homebrew,      tags: [ "homebrew",      "packages" ] }
    - { role: papertrail,    tags: [ "papertrail",    "packages" ] }
    - { role: zsh,           tags: [ "zsh",           "packages", "config" ] }
    - { role: dotfiles,      tags: [ "dotfiles",      "config" ] }

    # Roles specific to the environment desired on this Mac.
    - { role: composer,      tags: [ "composer",      "packages" ] }
    - { role: gem,           tags: [ "gem",           "packages" ] }
    - { role: yarn,          tags: [ "yarn",          "packages" ] }
    - { role: hashicorp,     tags: [ "hashicorp",     "packages" ] }
    - { role: go,            tags: [ "go",            "packages" ] }
    - { role: nginx,         tags: [ "nginx",         "packages", "config" ] }
    - { role: lastpass,      tags: [ "lastpass",      "packages" ] }

    # Finish-up roles.
    - { role: notifications, tags: [ "notifications" ] }

...
