---

# TODO: Finish this playbook!

# TODO: Support CentOS as well as Ubuntu for as many roles as possible (see ansible_os_family, ansible_pkg_mgr, ansible_distribution, ansible_distribution_file_variety, ansible_distribution_release, and ansible_distribution_version vars for help). See also the Ansible package module (https://docs.ansible.com/ansible/latest/modules/package_module.html).

# TODO: Work out how to determine whether the system was created today or not, and use that to determine whether a dist-upgrade should be run. Running `sudo tune2fs -l /dev/xvda1 | grep created` should give the created date of the filesystem which is a pretty good way to determine system age, and then there's a bunch of useful facts in {{ansible_date_time}} to compare to current.

# TODO: Because we're delaying the gathering of facts, work out how we can still gather facts if we're running with limited tags.

# TODO: Add documentation to each role. See the sample README.md structure in the apt role.

- hosts: aws, ubuntu
  become: yes
  gather_facts: no # This won't work until we install the needed Python module (see below).

  pre_tasks:

    # @see https://stackoverflow.com/a/34402816/1982136
    # @see https://docs.ansible.com/ansible/latest/modules/raw_module.html
    - name: Check if python-simplejson is installed.
      raw: dpkg-query --show python-simplejson
      register: python_simplejson_installed
      failed_when: python_simplejson_installed.rc > 1
      changed_when: python_simplejson_installed.rc == 1
      check_mode: no # Run even in 'check' mode; the command is safe and we need the output.

    - name: If not, install python-simplejson for Ansible support.
      raw: sudo apt-get install --assume-yes python-simplejson
      when: "python_simplejson_installed.rc == 1"

    - name: Gather facts now that the needed Python module is installed.
      setup: # No args required.

  roles:

    # Roles common across both Linux playbooks.
    - { role: apt,           tags: [ "apt",           "packages" ] }
    - { role: hostname,      tags: [ "hostname",      "config" ] }
    - { role: users-groups,  tags: [ "users-groups",  "config" ] }
    - { role: ssh,           tags: [ "ssh",           "config" ] }
    - { role: common,        tags: [ "common",        "config" ] }
    - { role: papertrail,    tags: [ "papertrail",    "packages" ] }
    - { role: datadog,       tags: [ "datadog",       "packages", "monitoring" ] }
    - { role: aws-ssm,       tags: [ "aws-ssm",       "packages", "monitoring" ] }
    - { role: dotfiles,      tags: [ "dotfiles",      "config" ] }

    # Roles specific to this playbook.
    - { role: composer,      tags: [ "composer",      "packages" ] }
    - { role: gem,           tags: [ "gem",           "packages" ] }
    - { role: yarn,          tags: [ "yarn",          "packages" ] }
    - { role: pip,           tags: [ "pip",           "packages" ] }
    - { role: wp-cli,        tags: [ "wp-cli",        "packages" ] }
    - { role: keybase,       tags: [ "keybase",       "packages" ] }
    - { role: hashicorp,     tags: [ "hashicorp",     "packages" ] }
    - { role: go,            tags: [ "go",            "packages" ] }
    - { role: mounts,        tags: [ "mounts",        "config" ] }
    - { role: nginx,         tags: [ "nginx",         "packages", "config" ] }
    - { role: lastpass,      tags: [ "lastpass",      "packages" ] }
    - { role: minikube,      tags: [ "minikube",      "packages" ] }
    - { role: ibm-cloud,     tags: [ "ibm-cloud",     "packages" ] }
    - { role: wordpress,     tags: [ "wordpress",     "web" ] }

    # Finish-up roles.
    - { role: notifications, tags: [ "notifications" ] }

    # TODO: Additional interesting roles to look into:
    #       - https://github.com/manala/ansible-role-accounts
    #       - https://github.com/manala/ansible-role-ansible
    #       - https://github.com/manala/ansible-role-ansible-galaxy
    #       - https://github.com/manala/ansible-role-cloud-init
    #       - https://github.com/manala/ansible-role-cron
    #       - https://github.com/manala/ansible-role-docker
    #       - https://github.com/manala/ansible-role-git
    #       - https://github.com/manala/ansible-role-logrotate
    #       - https://github.com/manala/ansible-role-mysql
    #       - https://github.com/manala/ansible-role-nginx
    #       - https://github.com/manala/ansible-role-ohmyzsh
    #       - https://github.com/manala/ansible-role-php
    #       - https://github.com/manala/ansible-role-phpmyadmin
    #       - https://github.com/manala/ansible-role-sudo
    #       - https://github.com/manala/ansible-role-systemd
    #       - https://github.com/manala/ansible-role-vim

...
