---

username: tim
full_name: Tim Malone
email: tdmalone@gmail.com
timezone: Australia/Melbourne
ssh_key: https://raw.githubusercontent.com/tdmalone/dotfiles/master/ssh.pub
ssh_port: "{{ lookup('env', 'SSH_PORT') }}"
shell: /bin/zsh

dotfiles_repo: https://github.com/tdmalone/dotfiles.git
zsh_theme_name: powerlevel9k
zsh_theme_repo: https://github.com/bhilburn/powerlevel9k.git

aws_region: ap-southeast-2

...
