---

# @see https://docs.ansible.com/ansible/latest/modules/command_module.html
# @see https://docs.ansible.com/ansible/latest/modules/get_url_module.html
# @see https://docs.ansible.com/ansible/latest/modules/yum_module.html

- name: Check if Oracle JRE 1.8 is installed...
  command: rpm --query jre1.8
  register: jre_is_installed
  failed_when: jre_is_installed.rc > 1
  changed_when: jre_is_installed.rc == 1
  check_mode: no # Run even in 'check' mode; the command is safe and we need the output.
  tags: skip_ansible_lint # Skip ANSIBLE0006, because rpm module does not provide --query option.
  args:
    warn: false # Again, skip because rpm module does not provide --query option.

- name: ...download Oracle JRE 1.8, then...
  get_url:
    url: "{{ jre_src }}"
    headers: "Cookie:oraclelicense=a"
    dest: /root/jre.rpm
  when: jre_is_installed.rc == 1

- name: ...install Oracle JRE.
  yum:
    name: /root/jre.rpm
  when: jre_is_installed.rc == 1

...
