---

# @see https://docs.ansible.com/ansible/latest/modules/lineinfile_module.html

# @see https://stackoverflow.com/questions/34661210/how-to-bind-kibana-to-multiple-host-names-ips
- name: Make Kibana available on all network interfaces.
  lineinfile:
    dest: /etc/kibana/kibana.yml
    regexp: "^#?server.host: "
    line: "server.host: \"0.0.0.0\""
  notify: restart kibana

...
